// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "35806e7c-769e-466b-89df-38cb3bb9b7ce");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1575371074);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1575371194);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1575370594);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1575370834);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1575370714);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1575370954);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1575371434);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1575371314);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 440320);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1575370564);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 77);
user_pref("browser.newtabpage.activity-stream.impressionId", "{db9324c7-bbc9-43e8-b55f-110f29855e5f}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1575360000);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1575370607919");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1575372398919");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1575370577425");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1575374177425");
user_pref("browser.search.region", "IN");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1575370569");
user_pref("browser.slowStartup.averageTime", 3722);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190215002044");
user_pref("browser.startup.homepage_override.mstone", "65.0.1");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 2);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1575370570715");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "65.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "a208fdde74204fb1bb5c199252f80deb");
user_pref("extensions.blocklist.lastModified", "Mon, 02 Dec 2019 11:14:55 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1575371078);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "65.0.1");
user_pref("extensions.lastPlatformVersion", "65.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"996a5028-b7e7-4895-b2f0-21dbfcecad58\",\"screenshots@mozilla.org\":\"73309886-dabc-4832-a281-d76066e2f8a5\",\"webcompat-reporter@mozilla.org\":\"f6734823-378d-4bd3-8694-68b060db5436\",\"webcompat@mozilla.org\":\"8e964d3d-f74f-4a23-b181-1b4a3a37def5\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1575370749);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20190215002044");
user_pref("media.gmp-manager.lastCheck", 1575370749);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "2d64416a-938a-40fa-b727-1588edf3f12c");
user_pref("security.sandbox.plugin.tempDirSuffix", "e400c444-8b94-4c9c-9aef-c270fe6f168d");
user_pref("services.blocklist.addons.checked", 1575370777);
user_pref("services.blocklist.gfx.checked", 1575370777);
user_pref("services.blocklist.onecrl.checked", 1575370777);
user_pref("services.blocklist.pinning.checked", 1575370777);
user_pref("services.blocklist.plugins.checked", 1575370777);
user_pref("services.settings.clock_skew_seconds", -76);
user_pref("services.settings.last_etag", "\"1575330556166\"");
user_pref("services.settings.last_update_seconds", 1575371030);
user_pref("services.settings.main.language-dictionaries.last_check", 1575370777);
user_pref("services.settings.main.sites-classification.last_check", 1575370777);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1575370562);
user_pref("toolkit.telemetry.cachedClientID", "fc78b538-c131-436f-9b1e-3644348ec82c");
user_pref("toolkit.telemetry.previousBuildID", "20190215002044");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
